name: Render Markdown to HTML and PDF

permissions:
  contents: write

on:
  push:
    paths: "index.qmd"
  workflow_dispatch:

jobs:
  render-markdown:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        tinytex: true

    - name: Install Ubuntu Font
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-ubuntu
        fc-cache -fv
        
    - name: Render Markdown to PDF
      uses: quarto-dev/quarto-actions/render@v2
      with:
        to: pdf
        path: index.qmd

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit and Push Changes
      run: |
        git add index.pdf
        git commit -m "Update index.pqf"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
